### Crear un nuevo tipo de proceso (Notariales)
POST http://localhost:9000/api/tipoprocesos
Content-Type: application/json

{
  "id_tipo": 1,
  "nombre": "Notariales"
}

### Crear un nuevo tipo de proceso (Juzgados)
POST http://localhost:9000/api/tipoprocesos
Content-Type: application/json

{
  "id_tipo": 2,
  "nombre": "Juzgados"
}

### Crear un nuevo tipo de proceso (Curadurías)
POST http://localhost:9000/api/tipoprocesos
Content-Type: application/json

{
  "id_tipo": 3,
  "nombre": "Curadurías"
}

### Obtener todos los tipos de proceso
GET http://localhost:9000/api/tipoprocesos

### Obtener un tipo de proceso por ID
GET http://localhost:9000/api/tipoprocesos/3

### Eliminar un tipo de proceso por ID
DELETE http://localhost:9000/api/tipoprocesos/3
