### Crear un cliente
POST http://localhost:9000/api/clientes
Content-Type: application/json

{
  "direccion": "123 Calle Falsa, Ciudad, País",
  "estado": "activo",
  "estado_cliente": "potencial",
  "numeroIdentificacion": "4561237890"
}

### Obtener un cliente por número de identificación
GET http://localhost:9000/api/clientes/4561237890


### Actualizar un cliente por número de identificación
PUT http://localhost:9000/api/clientes/4561237890
Content-Type: application/json

{
  "direccion": "Nueva dirección, Ciudad, País",
  "estado": "inactivo",  
  "estado_cliente": "cliente"  
}
