### Crear un nuevo usuario como abogado
POST http://localhost:9000/api/usuarios/create
Content-Type: application/json

{
  "numeroIdentificacion": "1029144521",
  "nombres": "Juan",
  "apellidos": "Diaz",
  "telefono": "3027786498",
  "email": "juan@example.com",
  "password": "segura123",
  "id_rol": "1"
}

### Crear un nuevo usuario como asistente
POST http://localhost:9000/api/usuarios/create
Content-Type: application/json

{
  "numeroIdentificacion": "1234567890",
  "nombres": "Alex",
  "apellidos": "Perdomo",
  "telefono": "7894561230",
  "email": "alex@example.com",
  "password": "segura123",
  "id_rol": "2"
}

### Crear un nuevo usuario como cliente
POST http://localhost:9000/api/usuarios/create
Content-Type: application/json

{
  "numeroIdentificacion": "4561237890",
  "nombres": "Leonardo",
  "apellidos": "Rivas",
  "telefono": "6598741212",
  "email": "leo@example.com",
  "password": "segura123",
  "id_rol": "3"
}


### Obtener todos los usuarios
GET http://localhost:9000/api/usuarios

### Obtener un usuario por su número de identificación
GET http://localhost:9000/api/usuarios/1234567890

### Actualizar un usuario
PUT http://localhost:9000/api/usuarios/1234567890
Content-Type: application/json

{
  "numeroIdentificacion": "1234567890",
  "nombres": "Alex",
  "apellidos": "Perdomo",
  "telefono": "7894561230",
  "email": "alex@gmail.com",
  "password": "segura123",
  "id_rol": "2"
}

### Eliminar un usuario
DELETE http://localhost:9000/api/usuarios/1029144521
